### ISSUE TITLE
Lizard Not Found

### ISSUE THREAD

**Issue by mho8** [laboon/quacc#10]
Recommend prefixing:

__Lizard__  
```shell
pip install lizard
```  

with sudo:

__Lizard__  
```shell
sudo pip install lizard
```  

in README.md  to avoid (obvious) mistake in installing dependencies (mismatch in PATH).

**Comment by minj131** [comment]
Ideally you want to use a virtual environment. You only want to use `sudo` or  elevated permissions when you want to install dependencies for the global, system-wide Python installation.
