### ISSUE TITLE
When trying to run './genhtml.py', get permission denied.

### ISSUE THREAD

**Issue by minj131** [laboon/quacc#5]

**Comment by minj131** [comment]
Quick fix for when getting permission denied error when trying to generate the html report. Make sure you're in the quacc directory.

`$ chmod +x -R .`

**Comment by laboon** [comment]
Note that this will change all files in this directory and all subdirectories recursively to have execute bit set.  Probably best to just do chmod +x genhtml.py unless that causes problems.

**Comment by minj131** [comment]
@laboon 

Setting genhtml.py only to executable runs the problem of having all the other scripts returning permission denied as well.

I guess we could just individually set the needed scripts to be executable if we want to avoid any issues that might arise from setting all the files.

**Comment by laboon** [comment]
It's not problematic to just do it to all of them.  Shouldn't cause any issues, just go ahead and do that.

**Comment by laboon** [comment]
This appears to be fixed for now, closing the issue.
