### ISSUE TITLE
Anton Ozaeta - Zcash

### ISSUE THREAD

**Issue by aro24** [laboon/quacc#6]
Switched from running Dogecoin to Zcash due to Dogecoin's missing dependencies (unable to sudo apt-get install libdb5.1-dev libdb5.1++-dev)

Meme is now a dream.

**Comment by laboon** [comment]
<img width="648" alt="screen shot 2018-09-21 at 12 35 46 pm" src="https://user-images.githubusercontent.com/1417717/45893955-f5b9ae00-bd9a-11e8-89f5-62fe546c7790.png">

**Comment by laboon** [comment]
Or you know, switch over to ZCash.  That's cool too.
